//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduClass.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avatar
    {
        public int Id { get; set; }
        public string UrlPhoto { get; set; }
        public string UpdatedAt { get; set; }
        public string Enabled { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
