//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduClass.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calification
    {
        public int Id { get; set; }
        public int Oral { get; set; }
        public int Test { get; set; }
        public int Other { get; set; }
        public double Average { get; set; }
        public int StudentId { get; set; }
        public int GroupId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Group Group { get; set; }
    }
}
