//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduClass.Entities
{
    using System;
    
    public enum EventType : int
    {
        Examen = 1,
        Entrega_trabajo = 2,
        Falta = 3,
        Otro = 4
    }
}
