SET PATHFOLDER=D:\code\Edu.Class\EduClass.Web\UsersFolders

mkdir %PATHFOLDER%\jarias 
mkdir %PATHFOLDER%\carlitosperez 
mkdir %PATHFOLDER%\mariapinto 
mkdir %PATHFOLDER%\enriques 
mkdir %PATHFOLDER%\jorherre 
mkdir %PATHFOLDER%\lrojas 
mkdir %PATHFOLDER%\roma 
mkdir %PATHFOLDER%\sofiredondo 
mkdir %PATHFOLDER%\yisustapia 
mkdir %PATHFOLDER%\alexgil 
mkdir %PATHFOLDER%\gonzabril 
mkdir %PATHFOLDER%\anaacero 
mkdir %PATHFOLDER%\luadame 
mkdir %PATHFOLDER%\camiadel 
mkdir %PATHFOLDER%\rabaeza 
mkdir %PATHFOLDER%\carmenbanda 
mkdir %PATHFOLDER%\abarbo 
mkdir %PATHFOLDER%\solbarra 
mkdir %PATHFOLDER%\edubazan 
mkdir %PATHFOLDER%\eugecalvo 
mkdir %PATHFOLDER%\emicamus 
mkdir %PATHFOLDER%\acanal 
mkdir %PATHFOLDER%\alecobos 
mkdir %PATHFOLDER%\alejandraolmo 
mkdir %PATHFOLDER%\arios 
mkdir %PATHFOLDER%\amandaroca 
mkdir %PATHFOLDER%\amparo 
mkdir %PATHFOLDER%\barbiegoya 
mkdir %PATHFOLDER%\belehera 
mkdir %PATHFOLDER%\elbenjakent 
mkdir %PATHFOLDER%\bleon 
mkdir %PATHFOLDER%\rikyara 
mkdir %PATHFOLDER%\juancaarbolea 
mkdir %PATHFOLDER%\majoazorero 
mkdir %PATHFOLDER%\cecibarbera 
mkdir %PATHFOLDER%\carmenbarreto 
mkdir %PATHFOLDER%\carlanegrete 
mkdir %PATHFOLDER%\crisquiroga 
mkdir %PATHFOLDER%\claudiosegui 
mkdir %PATHFOLDER%\diegonoguera 
mkdir %PATHFOLDER%\srosales 
mkdir %PATHFOLDER%\dariosalazar 
mkdir %PATHFOLDER%\dobregon 
mkdir %PATHFOLDER%\doranavarro 
mkdir %PATHFOLDER%\fabilatorre 
mkdir %PATHFOLDER%\fatiledesma 
mkdir %PATHFOLDER%\fedeescobar 
mkdir %PATHFOLDER%\feliencinas 
mkdir %PATHFOLDER%\feliserna 
mkdir %PATHFOLDER%\fernovoa 
mkdir %PATHFOLDER%\fromay 
mkdir %PATHFOLDER%\flaviaripol 
mkdir %PATHFOLDER%\francosalas 
mkdir %PATHFOLDER%\monirivas 
mkdir %PATHFOLDER%\gustavorosas 
mkdir %PATHFOLDER%\gabioliva 
mkdir %PATHFOLDER%\elguilleochoa 
mkdir %PATHFOLDER%\griselojeda 
mkdir %PATHFOLDER%\launieto 
mkdir %PATHFOLDER%\leandroneira 
mkdir %PATHFOLDER%\guilinadal 
mkdir %PATHFOLDER%\leticialemos 
mkdir %PATHFOLDER%\lulamas 
mkdir %PATHFOLDER%\lucashereas 
mkdir %PATHFOLDER%\lugodoy 
mkdir %PATHFOLDER%\luisgijon 
mkdir %PATHFOLDER%\walterrea 
mkdir %PATHFOLDER%\wendydoria 
mkdir %PATHFOLDER%\elbraian 
mkdir %PATHFOLDER%\walbertodonat 